// countries.js
export const countriesData = [
    { name: { common: "Afghanistan" }, cca2: "AF", currencies: { AFN: { name: "Afghan afghani" } }, capital: ["Kabul"] },
    { name: { common: "Albania" }, cca2: "AL", currencies: { ALL: { name: "Albanian lek" } }, capital: ["Tirana"] },
    { name: { common: "Algeria" }, cca2: "DZ", currencies: { DZD: { name: "Algerian dinar" } }, capital: ["Algiers"] },
    { name: { common: "Andorra" }, cca2: "AD", currencies: { EUR: { name: "Euro" } }, capital: ["Andorra la Vella"] },
    { name: { common: "Angola" }, cca2: "AO", currencies: { AOA: { name: "Angolan kwanza" } }, capital: ["Luanda"] },
    { name: { common: "Argentina" }, cca2: "AR", currencies: { ARS: { name: "Argentine peso" } }, capital: ["Buenos Aires"] },
    { name: { common: "Australia" }, cca2: "AU", currencies: { AUD: { name: "Australian dollar" } }, capital: ["Canberra"] },
    { name: { common: "Austria" }, cca2: "AT", currencies: { EUR: { name: "Euro" } }, capital: ["Vienna"] },
    { name: { common: "Bangladesh" }, cca2: "BD", currencies: { BDT: { name: "Bangladeshi taka" } }, capital: ["Dhaka"] },
    { name: { common: "Belgium" }, cca2: "BE", currencies: { EUR: { name: "Euro" } }, capital: ["Brussels"] },
    { name: { common: "Brazil" }, cca2: "BR", currencies: { BRL: { name: "Brazilian real" } }, capital: ["Brasília"] },
    { name: { common: "Canada" }, cca2: "CA", currencies: { CAD: { name: "Canadian dollar" } }, capital: ["Ottawa"] },
    { name: { common: "China" }, cca2: "CN", currencies: { CNY: { name: "Chinese yuan" } }, capital: ["Beijing"] },
    { name: { common: "Denmark" }, cca2: "DK", currencies: { DKK: { name: "Danish krone" } }, capital: ["Copenhagen"] },
    { name: { common: "Egypt" }, cca2: "EG", currencies: { EGP: { name: "Egyptian pound" } }, capital: ["Cairo"] },
    { name: { common: "Finland" }, cca2: "FI", currencies: { EUR: { name: "Euro" } }, capital: ["Helsinki"] },
    { name: { common: "France" }, cca2: "FR", currencies: { EUR: { name: "Euro" } }, capital: ["Paris"] },
    { name: { common: "Germany" }, cca2: "DE", currencies: { EUR: { name: "Euro" } }, capital: ["Berlin"] },
    { name: { common: "Greece" }, cca2: "GR", currencies: { EUR: { name: "Euro" } }, capital: ["Athens"] },
    { name: { common: "India" }, cca2: "IN", currencies: { INR: { name: "Indian rupee" } }, capital: ["New Delhi"] },
    { name: { common: "Indonesia" }, cca2: "ID", currencies: { IDR: { name: "Indonesian rupiah" } }, capital: ["Jakarta"] },
    { name: { common: "Italy" }, cca2: "IT", currencies: { EUR: { name: "Euro" } }, capital: ["Rome"] },
    { name: { common: "Japan" }, cca2: "JP", currencies: { JPY: { name: "Japanese yen" } }, capital: ["Tokyo"] },
    { name: { common: "Malaysia" }, cca2: "MY", currencies: { MYR: { name: "Malaysian ringgit" } }, capital: ["Kuala Lumpur"] },
    { name: { common: "Mexico" }, cca2: "MX", currencies: { MXN: { name: "Mexican peso" } }, capital: ["Mexico City"] },
    { name: { common: "Netherlands" }, cca2: "NL", currencies: { EUR: { name: "Euro" } }, capital: ["Amsterdam"] },
    { name: { common: "New Zealand" }, cca2: "NZ", currencies: { NZD: { name: "New Zealand dollar" } }, capital: ["Wellington"] },
    { name: { common: "Norway" }, cca2: "NO", currencies: { NOK: { name: "Norwegian krone" } }, capital: ["Oslo"] },
    { name: { common: "Philippines" }, cca2: "PH", currencies: { PHP: { name: "Philippine peso" } }, capital: ["Manila"] },
    { name: { common: "Poland" }, cca2: "PL", currencies: { PLN: { name: "Polish złoty" } }, capital: ["Warsaw"] },
    { name: { common: "Russia" }, cca2: "RU", currencies: { RUB: { name: "Russian ruble" } }, capital: ["Moscow"] },
    { name: { common: "Saudi Arabia" }, cca2: "SA", currencies: { SAR: { name: "Saudi riyal" } }, capital: ["Riyadh"] },
    { name: { common: "Singapore" }, cca2: "SG", currencies: { SGD: { name: "Singapore dollar" } }, capital: ["Singapore"] },
    { name: { common: "South Africa" }, cca2: "ZA", currencies: { ZAR: { name: "South African rand" } }, capital: ["Pretoria"] },
    { name: { common: "South Korea" }, cca2: "KR", currencies: { KRW: { name: "South Korean won" } }, capital: ["Seoul"] },
    { name: { common: "Spain" }, cca2: "ES", currencies: { EUR: { name: "Euro" } }, capital: ["Madrid"] },
    { name: { common: "Sweden" }, cca2: "SE", currencies: { SEK: { name: "Swedish krona" } }, capital: ["Stockholm"] },
    { name: { common: "Switzerland" }, cca2: "CH", currencies: { CHF: { name: "Swiss franc" } }, capital: ["Bern"] },
    { name: { common: "Thailand" }, cca2: "TH", currencies: { THB: { name: "Thai baht" } }, capital: ["Bangkok"] },
    { name: { common: "Turkey" }, cca2: "TR", currencies: { TRY: { name: "Turkish lira" } }, capital: ["Ankara"] },
    { name: { common: "United Arab Emirates" }, cca2: "AE", currencies: { AED: { name: "United Arab Emirates dirham" } }, capital: ["Abu Dhabi"] },
    { name: { common: "United Kingdom" }, cca2: "GB", currencies: { GBP: { name: "British pound" } }, capital: ["London"] },
    { name: { common: "United States" }, cca2: "US", currencies: { USD: { name: "United States dollar" } }, capital: ["Washington, D.C."] },
    { name: { common: "Vietnam" }, cca2: "VN", currencies: { VND: { name: "Vietnamese đồng" } }, capital: ["Hanoi"] }
];